/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SkillDescriptorJs {
  id: string
  description: string
  location: string
  userInvocable: boolean
}
export interface LoadedSkillJs {
  id: string
  name: string
  description: string
  allowedTools: Array<string>
  model?: string
  context?: string
  agent?: string
  userInvocable: boolean
  location: string
  instructions: string
}
export interface ExecutionOptionsJs {
  timeoutMs?: number
  memoryMb?: number
  input?: string
}
/** Options for targeted skill execution. */
export interface TargetExecutionOptionsJs {
  /** Target type: "auto", "script", or "wasm" */
  targetType?: string
  /** Path to script/wasm (required for "script" and "wasm" types) */
  path?: string
  /** Arguments for script execution (only for "script" type) */
  args?: Array<string>
  /** Override timeout in milliseconds */
  timeoutMs?: number
  /** Input data (JSON string) */
  input?: string
}
/** Permissions for sandboxed command execution. */
export interface CommandPermissionsJs {
  /** Allow network access. */
  allowNetwork?: boolean
  /** Allow subprocess spawning. */
  allowProcess?: boolean
  /** Directories the command can read from. */
  readPaths?: Array<string>
  /** Directories the command can write to. */
  writePaths?: Array<string>
  /** Environment variables to pass through (array of ["KEY", "VALUE"] pairs). */
  envVars?: Array<Array<string>>
  /** Timeout in milliseconds. */
  timeoutMs?: number
}
/** Result from sandboxed command execution. */
export interface CommandResultJs {
  /** Exit code (0 = success). */
  exitCode: number
  /** Captured stdout. */
  stdout: string
  /** Captured stderr. */
  stderr: string
  /** Whether the command timed out. */
  timedOut: boolean
}
export interface AuditRecord {
  skillId: string
  version: string
  inputHash: string
  outputHash: string
  startTimeMs: number
  durationMs: number
  permissionsUsed: Array<string>
  exitStatus: string
  stdout: string
  stderr: string
}
export interface ExecutionResult {
  outputJson: string
  stdout: string
  stderr: string
  audit: AuditRecord
}
/**
 * Run a shell command in a sandboxed environment (macOS only).
 *
 * This provides Claude Code-like sandboxed bash execution for agents.
 * Uses macOS Seatbelt sandbox-exec.
 */
export declare function runSandboxedShellCommand(command: string, workingDir: string, permissions?: CommandPermissionsJs | undefined | null): CommandResultJs
export declare class SkillExecutionSessionWrapper {
  isForked(): boolean
  contextId(): string | null
  recordToolCall(tool: string, outputJson: string): void
  recordResult(outputJson: string): void
  recordStdout(stdout: string): void
  recordStderr(stderr: string): void
  summarize(): string
}
export declare class ExecutionContextWrapper {
  constructor()
  fork(): ExecutionContextWrapper
  id(): string
  isForked(): boolean
  parentId(): string | null
  summary(): string | null
  recordOutput(outputType: string, content: string): void
  summarize(): string
}
export declare class OpenSkillRuntimeWrapper {
  constructor()
  static withProjectRoot(projectRoot: string): OpenSkillRuntimeWrapper
  static fromDirectory(skillsDir: string): OpenSkillRuntimeWrapper
  /** Create runtime with custom directories and configuration */
  static withCustomDirectories(customDirectories: Array<string>, useStandardLocations?: boolean | undefined | null, projectRoot?: string | undefined | null): OpenSkillRuntimeWrapper
  /** Discover skills from standard locations (~/.claude/skills/, .claude/skills/, nested) */
  discoverSkills(): Array<SkillDescriptorJs>
  /** Load skills from a specific directory (additive - can be called multiple times) */
  loadFromDirectory(dir: string): Array<SkillDescriptorJs>
  /** List skills (progressive disclosure - descriptors only) */
  listSkills(): Array<SkillDescriptorJs>
  /** Activate a skill (load full SKILL.md content) */
  activateSkill(skillId: string): LoadedSkillJs
  /** Execute a skill's WASM module */
  executeSkill(skillId: string, options?: ExecutionOptionsJs | undefined | null): ExecutionResult
  /** Start an instruction-based skill session (for context: fork behavior). */
  startSkillSession(skillId: string, inputJson?: string | undefined | null, parentContext?: ExecutionContextWrapper | undefined | null): SkillExecutionSessionWrapper
  /** Finish a skill session and return an ExecutionResult. */
  finishSkillSession(session: SkillExecutionSessionWrapper, outputJson: string, stdout: string, stderr: string, exitStatus?: string | undefined | null): ExecutionResult
  /** Check if a tool is allowed for a skill */
  isToolAllowed(skillId: string, tool: string): boolean
  /** Check if a tool call is permitted for a skill (ask-before-act for risky tools). */
  checkToolPermission(skillId: string, tool: string, description?: string | undefined | null): boolean
  /**
   * Run a specific target (script/WASM) within a skill.
   *
   * This is designed for Claude Skills where SKILL.md instructions tell
   * the agent which script to run (e.g., "run python ooxml/scripts/unpack.py").
   */
  runSkillTarget(skillId: string, options?: TargetExecutionOptionsJs | undefined | null): ExecutionResult
  /**
   * Read a file from a skill directory.
   *
   * This allows agents to read helper files (like `docx-js.md`) that skills
   * reference in their SKILL.md instructions.
   */
  readSkillFile(skillId: string, relativePath: string): string
  /**
   * List files in a skill directory (or subdirectory).
   *
   * Returns relative paths from the skill root.
   */
  listSkillFiles(skillId: string, subdir?: string | undefined | null, recursive?: boolean | undefined | null): Array<string>
  /** Get the root directory path for a skill. */
  getSkillRoot(skillId: string): string
}

export type OpenSkillRuntime = OpenSkillRuntimeWrapper
export const OpenSkillRuntime: typeof OpenSkillRuntimeWrapper
