#!/usr/bin/env node

/**
 * Post-build script to add OpenSkillRuntime alias exports to index.js and index.d.ts
 * This is needed because these files are auto-generated by napi-rs and don't include this alias
 */

const fs = require('fs');
const path = require('path');

const bindingsDir = path.join(__dirname, '..');
const indexJsPath = path.join(bindingsDir, 'index.js');
const indexDtsPath = path.join(bindingsDir, 'index.d.ts');

// Process index.js
if (fs.existsSync(indexJsPath)) {
  const jsContent = fs.readFileSync(indexJsPath, 'utf8');

  // Check if the alias already exists
  if (jsContent.includes('module.exports.OpenSkillRuntime = OpenSkillRuntimeWrapper')) {
    console.log('OpenSkillRuntime alias already exists in index.js');
  } else if (jsContent.includes('module.exports.OpenSkillRuntimeWrapper = OpenSkillRuntimeWrapper')) {
    // Add the alias export if it doesn't exist
    const newContent = jsContent.replace(
      /module\.exports\.OpenSkillRuntimeWrapper = OpenSkillRuntimeWrapper$/m,
      'module.exports.OpenSkillRuntimeWrapper = OpenSkillRuntimeWrapper\nmodule.exports.OpenSkillRuntime = OpenSkillRuntimeWrapper'
    );
    fs.writeFileSync(indexJsPath, newContent, 'utf8');
    console.log('Added OpenSkillRuntime alias to index.js');
  } else {
    console.warn('Could not find OpenSkillRuntimeWrapper export to add alias in index.js');
  }
} else {
  console.warn('index.js not found, skipping');
}

// Process index.d.ts
if (fs.existsSync(indexDtsPath)) {
  let dtsContent = fs.readFileSync(indexDtsPath, 'utf8');
  let modified = false;

  // Check if the exports already exist
  const hasTypeExport = dtsContent.includes('export type OpenSkillRuntime = OpenSkillRuntimeWrapper');
  const hasConstExport = dtsContent.includes('export const OpenSkillRuntime: typeof OpenSkillRuntimeWrapper');

  if (hasTypeExport && hasConstExport) {
    console.log('OpenSkillRuntime exports already exist in index.d.ts');
  } else {
    // Add missing exports at the end of the file
    const exportsToAdd = [];
    if (!hasTypeExport) {
      exportsToAdd.push('export type OpenSkillRuntime = OpenSkillRuntimeWrapper');
    }
    if (!hasConstExport) {
      exportsToAdd.push('export const OpenSkillRuntime: typeof OpenSkillRuntimeWrapper');
    }
    
    if (exportsToAdd.length > 0) {
      // Ensure file ends with newline, then add exports
      if (!dtsContent.endsWith('\n')) {
        dtsContent += '\n';
      }
      dtsContent += '\n' + exportsToAdd.join('\n') + '\n';
      fs.writeFileSync(indexDtsPath, dtsContent, 'utf8');
      console.log('Added OpenSkillRuntime exports to index.d.ts');
    }
  }
} else {
  console.warn('index.d.ts not found, skipping');
}
