#!/usr/bin/env node

/**
 * Post-build script to add OpenSkillRuntime alias export to index.js
 * This is needed because index.js is auto-generated by napi-rs and doesn't include this alias
 */

const fs = require('fs');
const path = require('path');

const indexJsPath = path.join(__dirname, '..', 'index.js');

if (!fs.existsSync(indexJsPath)) {
  console.error('index.js not found, skipping postbuild');
  process.exit(0);
}

const content = fs.readFileSync(indexJsPath, 'utf8');

// Check if the alias already exists
if (content.includes('module.exports.OpenSkillRuntime = OpenSkillRuntimeWrapper')) {
  console.log('OpenSkillRuntime alias already exists in index.js');
  process.exit(0);
}

// Add the alias export if it doesn't exist
if (content.includes('module.exports.OpenSkillRuntimeWrapper = OpenSkillRuntimeWrapper')) {
  const newContent = content.replace(
    /module\.exports\.OpenSkillRuntimeWrapper = OpenSkillRuntimeWrapper$/m,
    'module.exports.OpenSkillRuntimeWrapper = OpenSkillRuntimeWrapper\nmodule.exports.OpenSkillRuntime = OpenSkillRuntimeWrapper'
  );
  fs.writeFileSync(indexJsPath, newContent, 'utf8');
  console.log('Added OpenSkillRuntime alias to index.js');
} else {
  console.warn('Could not find OpenSkillRuntimeWrapper export to add alias');
}
