#!/usr/bin/env node

/**
 * Post-build script to add OpenSkillRuntime alias exports to index.js and index.d.ts
 * This is needed because these files are auto-generated by napi-rs and don't include this alias
 */

const fs = require('fs');
const path = require('path');

const bindingsDir = path.join(__dirname, '..');
const indexJsPath = path.join(bindingsDir, 'index.js');
const indexDtsPath = path.join(bindingsDir, 'index.d.ts');

// Process index.js
if (fs.existsSync(indexJsPath)) {
  const jsContent = fs.readFileSync(indexJsPath, 'utf8');

  // Check if the alias already exists
  if (jsContent.includes('module.exports.OpenSkillRuntime = OpenSkillRuntimeWrapper')) {
    console.log('OpenSkillRuntime alias already exists in index.js');
  } else if (jsContent.includes('module.exports.OpenSkillRuntimeWrapper = OpenSkillRuntimeWrapper')) {
    // Add the alias export if it doesn't exist
    const newContent = jsContent.replace(
      /module\.exports\.OpenSkillRuntimeWrapper = OpenSkillRuntimeWrapper$/m,
      'module.exports.OpenSkillRuntimeWrapper = OpenSkillRuntimeWrapper\nmodule.exports.OpenSkillRuntime = OpenSkillRuntimeWrapper'
    );
    fs.writeFileSync(indexJsPath, newContent, 'utf8');
    console.log('Added OpenSkillRuntime alias to index.js');
  } else {
    console.warn('Could not find OpenSkillRuntimeWrapper export to add alias in index.js');
  }
} else {
  console.warn('index.js not found, skipping');
}

// Process index.d.ts
if (fs.existsSync(indexDtsPath)) {
  const dtsContent = fs.readFileSync(indexDtsPath, 'utf8');

  // Check if the value export already exists
  if (dtsContent.includes('export const OpenSkillRuntime: typeof OpenSkillRuntimeWrapper')) {
    console.log('OpenSkillRuntime value export already exists in index.d.ts');
  } else if (dtsContent.includes('export type OpenSkillRuntime = OpenSkillRuntimeWrapper')) {
    // Add the value export declaration if it doesn't exist
    const newContent = dtsContent.replace(
      /export type OpenSkillRuntime = OpenSkillRuntimeWrapper$/m,
      'export type OpenSkillRuntime = OpenSkillRuntimeWrapper\nexport const OpenSkillRuntime: typeof OpenSkillRuntimeWrapper'
    );
    fs.writeFileSync(indexDtsPath, newContent, 'utf8');
    console.log('Added OpenSkillRuntime value export to index.d.ts');
  } else {
    console.warn('Could not find OpenSkillRuntime type export to add value export in index.d.ts');
  }
} else {
  console.warn('index.d.ts not found, skipping');
}
